apiVersion: v1
kind: Pod

metadata:
  name: k8s-kms-plugin-server-test
  labels:
    app.kubernetes.io/name: k8s-kms-plugin-server-test
spec:
  volumes:
    - name: certstore
      emptyDir: {}
    - name: ca
      hostPath:
        path: /etc/
    - name: socket
      emptyDir: {}
    - name: logs
      emptyDir: {}
  containers:
    - name: e2e-test
      image: "docker.io/linggg/hsm-plugin:20200807-1"
      imagePullPolicy: IfNotPresent
      command:
        - /k8s-kms-plugin
        - test
        - --loop=true
      volumeMounts:
        - mountPath: /tmp/run
          name: socket
